//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public class_data()
        {
            this.data_proccess = new HashSet<data_proccess>();
        }
    
        public int id { get; set; }
        public string code_class { get; set; }
        public string name_class { get; set; }
        public string location { get; set; }
        public string number_of_type { get; set; }
        public string nsn { get; set; }
        public string s { get; set; }
        public string d { get; set; }
        public string mother_group { get; set; }
        public string store_group { get; set; }
        public Nullable<int> store_capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data_proccess> data_proccess { get; set; }
    }
}
